%YAML:1.0
---
camera1:
  name: "car_left"
  rotate_angle: 0
  device_id: 4
  width: 800
  height: 480
  publish_image: true
  frame_id: "car_left"

camera0:
  name: "backward_right"
  rotate_angle: 180
  device_id: 2
  width: 800
  height: 480
  publish_image: true
  frame_id: "backward_right"

camera2:
  name: "backward_left"
  rotate_angle: 180
  device_id: 0
  width: 800
  height: 480
  publish_image: true
  frame_id: "backward_left"